calanguage: python
sudo: required
dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - CIRQ_VERSION="cirq>=0.7,<0.8"
  - CIRQ_VERSION="cirq>=0.8"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda install -c conda-forge lapack
  - conda install -c cvxgrp cvxpy=1.0.24
  - conda list
  - pip install -q -U $CIRQ_VERSION
  - pip install -q -r requirements.txt
  - pip install -q -r extra-requirements.txt
  - pip install .

script:
  - QUANTUMFLOW_BACKEND=numpy python -m quantumflow.meta
  - QUANTUMFLOW_BACKEND=numpy pytest --disable-pytest-warnings --cov=quantumflow --cov-config .toxcoveragerc --cov-fail-under 100  --cov-report term-missing tests/
  - QUANTUMFLOW_BACKEND=tensorflow python -m quantumflow.meta
  - QUANTUMFLOW_BACKEND=tensorflow pytest --disable-pytest-warnings
  - flake8 quantumflow examples tests tools setup.py
  - mypy -p quantumflow --ignore-missing-imports
  - sphinx-build -M html docs docs/_build

