calanguage: python
sudo: required
dist: xenial

python:
  - "3.7"  
  - "3.8"

before_install:
  - pip install -U pip

install:
  - pip install .[dev]  # install package + test dependencies

script:
  - python -m quantumflow.about
  - python -m pytest --cov=quantumflow --cov-fail-under 100
  - flake8
  - mypy quantumflow
  - sphinx-build -M html docs docs/_build
